import type { AuthUser as User } from '@/features/auth/types';
import type { Permission } from './permissions';

/**
 * Minimal role-to-permissions fallback mapping.
 * Used only when RBAC permissions from API are not available yet.
 */
const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  admin: [
    'tenant.members.list',
    'tenant.members.view',
    'tenant.members.add',
    'tenant.members.update',
    'tenant.members.remove',
    'tenant.invitations.list',
    'tenant.invitations.create',
    'tenant.invitations.cancel',
    'tenant.invitations.resend',
    'tenant.organizations.list',
    'tenant.organizations.view',
    'tenant.organizations.update',
    'tenant.organizations.manage_settings',
    'documents.list',
    'documents.view',
    'documents.create',
    'documents.update',
    'documents.delete',
    'analytics.dashboard.view',
    'analytics.reports.view',
    'analytics.reports.send',
    'projects.list',
    'projects.view',
    'projects.create',
    'projects.update',
    'projects.delete',
    'projects.members.manage',
    'projects.members.list',
    'projects.members.update',
    'projects.members.remove',
    'projects.statuses.list',
    'projects.statuses.create',
    'projects.statuses.update',
    'projects.statuses.delete',
    'projects.tasks.list',
    'projects.tasks.view',
    'projects.tasks.create',
    'projects.tasks.update',
    'projects.tasks.assign',
    'projects.tasks.change_status',
    'projects.tasks.delete',
    'projects.attachments.list',
    'projects.attachments.upload',
    'projects.attachments.delete',
    'projects.roles.list',
    'projects.roles.view',
    'projects.roles.create',
    'projects.roles.update',
    'projects.roles.delete',
    'projects.roles.assign_permissions',
    'projects.roles.revoke_permissions',
    'projects.roles.assign_to_member',
    'projects.roles.revoke_from_member',
    'rbac.roles.list',
    'rbac.roles.view',
    'rbac.roles.create',
    'rbac.roles.update',
    'rbac.roles.delete',
    'rbac.roles.assign_permissions',
    'rbac.roles.revoke_permissions',
    'rbac.user_roles.list',
    'rbac.user_roles.view',
    'rbac.user_roles.assign',
    'rbac.user_roles.revoke',
    'rbac.permissions.list',
    'rbac.permissions.view',
    'analytics.kpi.org.view',
    'analytics.kpi.target.manage',
    'analytics.kpi.target.view',
    'analytics.kpi.project.view',
    'analytics.reports.view',
    'analytics.reports.send',
    'org_config.settings.view',
    'org_config.settings.manage',
    'org_config.working_time.view',
    'org_config.working_time.manage',
    'billing.subscriptions.view',
    'billing.subscriptions.create',
    'billing.subscriptions.cancel',
    'billing.subscriptions.change_plan',
    'billing.invoices.list',
  ],
  member: [
    'documents.list',
    'documents.view',
    'documents.create',
    'analytics.dashboard.view',
    'projects.list',
    'projects.view',
    'projects.tasks.list',
    'projects.tasks.view',
    'projects.tasks.create',
    'projects.tasks.update',
    'projects.tasks.change_status',
    'projects.attachments.list',
    'projects.attachments.upload',
  ],
  viewer: [
    'documents.list',
    'documents.view',
    'analytics.dashboard.view',
    'projects.list',
    'projects.view',
    'projects.tasks.list',
    'projects.tasks.view',
    'projects.attachments.list',
  ],
};

/**
 * Check if a user has a given permission via role-based policy fallback.
 */
export function can(user: User | null, permission: Permission): boolean {
  if (!user) return false;
  const permissions = ROLE_PERMISSIONS[user.role] ?? [];
  return permissions.includes(permission);
}
